import { getAuthenticatedSpotifyApi } from '$lib/server/spotify/spotify';
import type { TrackWithAlbum } from '@spotify/web-api-ts-sdk/dist/mjs/types';
import type { PageServerLoad } from '../$types';
import { getTopItems } from '@ekwoka/spotify-api';

export const load: PageServerLoad = async () => {
  const api = await getAuthenticatedSpotifyApi();
  const response = await api(
    getTopItems('tracks', { time_range: 'medium_term' })
  );
  return { topTracks: response?.items as unknown as TrackWithAlbum[] };
};

/**
 * Static content that gets recalculated every 12 hours (ish)
 */
export const csr = false;
export const config = {
  isr: {
    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: 60 * 60 * 12,
  },
};
