import { getAuthenticatedSpotifyApi } from '$lib/server/spotify/spotify';
import type { PageServerLoad } from '../$types';

export const load: PageServerLoad = async () => {
  const api = await getAuthenticatedSpotifyApi();
  const response = await api.getMyTopTracks({ time_range: 'short_term' });
  return { topTracks: response.body?.items };
};

/**
 * Static content that gets recalculated every 12 hours (ish)
 */
export const csr = false;
export const config = {
  isr: {
    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: 60 * 60 * 12,
  },
};
